.ci_support/linux_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/linux_ppc64le_.yaml
recipe/activate-g++.sh
recipe/activate-gcc.sh
recipe/activate-gfortran.sh
recipe/conda_build_config.yaml
recipe/deactivate-g++.sh
recipe/deactivate-gcc.sh
recipe/deactivate-gfortran.sh

ENH use -isystem everywhere

---

.ci_support/linux_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/linux_ppc64le_.yaml
recipe/conda_build_config.yaml

Update binutils version to 2.34

---

.azure-pipelines/azure-pipelines-linux.yml
.ci_support/linux_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/linux_ppc64le_.yaml
.drone.yml
.github/workflows/automerge.yml
.scripts/build_steps.sh
.scripts/run_docker_build.sh
README.md
recipe/conda_build_config.yaml

Update ppc64le version

---

.azure-pipelines/azure-pipelines-linux.yml
.ci_support/linux_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/linux_ppc64le_.yaml
.drone.yml
.github/CODEOWNERS
.scripts/build_steps.sh
.scripts/run_docker_build.sh
.travis.yml
README.md
recipe/conda_build_config.yaml
recipe/meta.yaml

ENH use new sysroot

---

.ci_support/linux_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/linux_ppc64le_.yaml
recipe/activate-binutils.sh
recipe/conda_build_config.yaml
recipe/deactivate-binutils.sh

BUG set BUILD env var

---

.azure-pipelines/azure-pipelines-linux.yml
.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/linux_ppc64le_.yaml
LICENSE.txt
README.md

Hi! This is the friendly automated conda-forge-webservice.
I've rerendered the recipe as instructed in #27.
Here's a checklist to do before merging.
Fixes #27

MNT: rerender

---

recipe/activate-gcc.sh
recipe/conda_build_config.yaml
recipe/deactivate-gcc.sh

Set QEMU_LD_PREFIX for emulation

---

.ci_support/linux_64_conda_glibc_ver2.12ctng_gcc7.5.0ctng_target_platformlinux-64target_platformlinux-64.yaml
.ci_support/linux_64_conda_glibc_ver2.12ctng_gcc8.4.0ctng_target_platformlinux-64target_platformlinux-64.yaml
.ci_support/linux_64_conda_glibc_ver2.12ctng_gcc9.3.0ctng_target_platformlinux-64target_platformlinux-64.yaml
.ci_support/linux_64_conda_glibc_ver2.17ctng_gcc7.5.0ctng_target_platformlinux-aarch64target_platformlinux-64.yaml
.ci_support/linux_64_conda_glibc_ver2.17ctng_gcc7.5.0ctng_target_platformlinux-ppc64letarget_platformlinux-64.yaml
.ci_support/linux_64_conda_glibc_ver2.17ctng_gcc8.4.0ctng_target_platformlinux-aarch64target_platformlinux-64.yaml
.ci_support/linux_64_conda_glibc_ver2.17ctng_gcc8.4.0ctng_target_platformlinux-ppc64letarget_platformlinux-64.yaml
.ci_support/linux_64_conda_glibc_ver2.17ctng_gcc9.3.0ctng_target_platformlinux-aarch64target_platformlinux-64.yaml
.ci_support/linux_64_conda_glibc_ver2.17ctng_gcc9.3.0ctng_target_platformlinux-ppc64letarget_platformlinux-64.yaml
.ci_support/linux_aarch64_conda_glibc_ver2.17ctng_gcc7.5.0ctng_target_platformlinux-aarch64target_platformlinux-aarch64.yaml
.ci_support/linux_aarch64_conda_glibc_ver2.17ctng_gcc8.4.0ctng_target_platformlinux-aarch64target_platformlinux-aarch64.yaml
.ci_support/linux_aarch64_conda_glibc_ver2.17ctng_gcc9.3.0ctng_target_platformlinux-aarch64target_platformlinux-aarch64.yaml
.ci_support/linux_ppc64le_conda_glibc_ver2.17ctng_gcc7.5.0ctng_target_platformlinux-ppc64letarget_platformlinux-ppc64le.yaml
.ci_support/linux_ppc64le_conda_glibc_ver2.17ctng_gcc8.4.0ctng_target_platformlinux-ppc64letarget_platformlinux-ppc64le.yaml
.ci_support/linux_ppc64le_conda_glibc_ver2.17ctng_gcc9.3.0ctng_target_platformlinux-ppc64letarget_platformlinux-ppc64le.yaml
recipe/conda_build_config.yaml
recipe/meta.yaml

REF use soname for libgfortran

---

.azure-pipelines/azure-pipelines-linux.yml
.ci_support/linux_64_conda_glibc_ver2.12ctng_gcc7.5.0ctng_target_platformlinux-64.yaml
.ci_support/linux_64_conda_glibc_ver2.12ctng_gcc8.4.0ctng_target_platformlinux-64.yaml
.ci_support/linux_64_conda_glibc_ver2.12ctng_gcc9.3.0ctng_target_platformlinux-64.yaml
.ci_support/linux_64_conda_glibc_ver2.17ctng_gcc7.5.0ctng_target_platformlinux-aarch64.yaml
.ci_support/linux_64_conda_glibc_ver2.17ctng_gcc7.5.0ctng_target_platformlinux-ppc64le.yaml
.ci_support/linux_64_conda_glibc_ver2.17ctng_gcc8.4.0ctng_target_platformlinux-aarch64.yaml
.ci_support/linux_64_conda_glibc_ver2.17ctng_gcc8.4.0ctng_target_platformlinux-ppc64le.yaml
.ci_support/linux_64_conda_glibc_ver2.17ctng_gcc9.3.0ctng_target_platformlinux-aarch64.yaml
.ci_support/linux_64_conda_glibc_ver2.17ctng_gcc9.3.0ctng_target_platformlinux-ppc64le.yaml
.ci_support/linux_aarch64_conda_glibc_ver2.17ctng_gcc7.5.0ctng_target_platformlinux-aarch64.yaml
.ci_support/linux_aarch64_conda_glibc_ver2.17ctng_gcc8.4.0ctng_target_platformlinux-aarch64.yaml
.ci_support/linux_aarch64_conda_glibc_ver2.17ctng_gcc9.3.0ctng_target_platformlinux-aarch64.yaml
.ci_support/linux_ppc64le_conda_glibc_ver2.17ctng_gcc7.5.0ctng_target_platformlinux-ppc64le.yaml
.ci_support/linux_ppc64le_conda_glibc_ver2.17ctng_gcc8.4.0ctng_target_platformlinux-ppc64le.yaml
.ci_support/linux_ppc64le_conda_glibc_ver2.17ctng_gcc9.3.0ctng_target_platformlinux-ppc64le.yaml
.drone.yml
.scripts/build_steps.sh
.scripts/run_docker_build.sh
.travis.yml
README.md
build-locally.py
recipe/activate-gcc.sh
recipe/conda_build_config.yaml
recipe/deactivate-gcc.sh

BUG make sure to not munge prompt on zsh

---

.ci_support/linux_64_conda_glibc_ver2.12ctng_gcc7.5.0ctng_target_platformlinux-64.yaml
.ci_support/linux_64_conda_glibc_ver2.12ctng_gcc8.4.0ctng_target_platformlinux-64.yaml
.ci_support/linux_64_conda_glibc_ver2.12ctng_gcc9.3.0ctng_target_platformlinux-64.yaml
.ci_support/linux_64_conda_glibc_ver2.17ctng_gcc7.5.0ctng_target_platformlinux-aarch64.yaml
.ci_support/linux_64_conda_glibc_ver2.17ctng_gcc7.5.0ctng_target_platformlinux-ppc64le.yaml
.ci_support/linux_64_conda_glibc_ver2.17ctng_gcc8.4.0ctng_target_platformlinux-aarch64.yaml
.ci_support/linux_64_conda_glibc_ver2.17ctng_gcc8.4.0ctng_target_platformlinux-ppc64le.yaml
.ci_support/linux_64_conda_glibc_ver2.17ctng_gcc9.3.0ctng_target_platformlinux-aarch64.yaml
.ci_support/linux_64_conda_glibc_ver2.17ctng_gcc9.3.0ctng_target_platformlinux-ppc64le.yaml
.ci_support/linux_aarch64_conda_glibc_ver2.17ctng_gcc7.5.0ctng_target_platformlinux-aarch64.yaml
.ci_support/linux_aarch64_conda_glibc_ver2.17ctng_gcc8.4.0ctng_target_platformlinux-aarch64.yaml
.ci_support/linux_aarch64_conda_glibc_ver2.17ctng_gcc9.3.0ctng_target_platformlinux-aarch64.yaml
.ci_support/linux_ppc64le_conda_glibc_ver2.17ctng_gcc7.5.0ctng_target_platformlinux-ppc64le.yaml
.ci_support/linux_ppc64le_conda_glibc_ver2.17ctng_gcc8.4.0ctng_target_platformlinux-ppc64le.yaml
.ci_support/linux_ppc64le_conda_glibc_ver2.17ctng_gcc9.3.0ctng_target_platformlinux-ppc64le.yaml
recipe/conda_build_config.yaml
recipe/meta.yaml

Use only impl in bootstrap package

---

recipe/conda_build_config.yaml
recipe/meta.yaml

don't relocate sysroot files

---

recipe/build.sh
recipe/get_cpu_arch.sh
recipe/install-symlinks.sh
recipe/meta.yaml

Add symlinks

---

LICENSE.txt
recipe/conda_build_config.yaml
recipe/meta.yaml

Checklist
This addresses https://github.com/conda-forge/gdal-feedstock/pull/604#discussion_r806066286

Add allow-shlib-undefined to linux ldflags

---

.azure-pipelines/azure-pipelines-linux.yml
.ci_support/linux_64_conda_glibc_ver2.12ctng_gcc12.1.0ctng_target_platformlinux-64.yaml
.ci_support/linux_64_conda_glibc_ver2.17ctng_gcc12.1.0ctng_target_platformlinux-aarch64.yaml
.ci_support/linux_64_conda_glibc_ver2.17ctng_gcc12.1.0ctng_target_platformlinux-ppc64le.yaml
.ci_support/linux_64_conda_glibc_ver2.17ctng_gcc12.1.0ctng_target_platformlinux-s390x.yaml
.ci_support/linux_aarch64_conda_glibc_ver2.12ctng_gcc12.1.0ctng_target_platformlinux-64.yaml
.ci_support/linux_aarch64_conda_glibc_ver2.17ctng_gcc12.1.0ctng_target_platformlinux-aarch64.yaml
.ci_support/linux_aarch64_conda_glibc_ver2.17ctng_gcc12.1.0ctng_target_platformlinux-ppc64le.yaml
.ci_support/linux_aarch64_conda_glibc_ver2.17ctng_gcc12.1.0ctng_target_platformlinux-s390x.yaml
.ci_support/linux_ppc64le_conda_glibc_ver2.12ctng_gcc12.1.0ctng_target_platformlinux-64.yaml
.ci_support/linux_ppc64le_conda_glibc_ver2.17ctng_gcc12.1.0ctng_target_platformlinux-aarch64.yaml
.ci_support/linux_ppc64le_conda_glibc_ver2.17ctng_gcc12.1.0ctng_target_platformlinux-ppc64le.yaml
.ci_support/linux_ppc64le_conda_glibc_ver2.17ctng_gcc12.1.0ctng_target_platformlinux-s390x.yaml
.ci_support/linux_s390x_conda_glibc_ver2.12ctng_gcc12.1.0ctng_target_platformlinux-64.yaml
.ci_support/linux_s390x_conda_glibc_ver2.17ctng_gcc12.1.0ctng_target_platformlinux-aarch64.yaml
.ci_support/linux_s390x_conda_glibc_ver2.17ctng_gcc12.1.0ctng_target_platformlinux-ppc64le.yaml
.ci_support/linux_s390x_conda_glibc_ver2.17ctng_gcc12.1.0ctng_target_platformlinux-s390x.yaml
.circleci/config.yml
README.md
recipe/conda_build_config.yaml

Checklist
Fixes https://github.com/conda-forge/compilers-feedstock/issues/48

Add gcc 12.1.0 and drop 8.5.0

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.scripts/create_conda_build_artifacts.sh
README.md
conda-forge.yml
recipe/build.sh
recipe/meta.yaml

Follow-up from #102, see [here](https://github.com/conda-forge/ctng-compiler-activation-feedstock/pull/102#discussion_r1520749310)

fix incorrect compiler activation

---

recipe/meta.yaml

Fix build numbers

---

recipe/activate-binutils.sh
recipe/build.sh
recipe/deactivate-binutils.sh
recipe/meta.yaml
recipe/tests/aligned_alloc.c
recipe/tests/aligned_alloc.cpp

Fix windows build

---

recipe/meta.yaml

Include target_platform compilers in gcc bootstrap

---

recipe/activate-binutils.sh
recipe/activate-g++.sh
recipe/activate-gcc.sh
recipe/build.sh
recipe/deactivate-binutils.sh
recipe/deactivate-g++.sh
recipe/deactivate-gcc.sh
recipe/meta.yaml

Fix slashes in conda for windows

---

recipe/meta.yaml

Add gendef for win-64 cross compilers

---

recipe/activate-binutils.bat

Fix binutils activation

---

recipe/meta.yaml

Remove binutils

---

recipe/activate-gfortran.sh
recipe/meta.yaml

Checklist
* ~~Reset the build number to `0` (if the version changed)~~
Closes https://github.com/conda-forge/ctng-compiler-activation-feedstock/issues/137
Introduced by https://github.com/conda-forge/ctng-compiler-activation-feedstock/pull/136

Include without space

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_cross_target_platformlinux-64gcc_version15.1.0.yaml
.ci_support/linux_64_cross_target_platformlinux-aarch64gcc_version15.1.0.yaml
.ci_support/linux_64_cross_target_platformlinux-ppc64legcc_version15.1.0.yaml
.ci_support/linux_64_cross_target_platformwin-64gcc_version15.1.0.yaml
.ci_support/linux_aarch64_cross_target_platformlinux-64gcc_version15.1.0.yaml
.ci_support/linux_aarch64_cross_target_platformlinux-aarch64gcc_version15.1.0.yaml
.ci_support/linux_aarch64_cross_target_platformlinux-ppc64legcc_version15.1.0.yaml
.ci_support/linux_aarch64_cross_target_platformwin-64gcc_version15.1.0.yaml
.ci_support/linux_ppc64le_cross_target_platformlinux-64gcc_version15.1.0.yaml
.ci_support/linux_ppc64le_cross_target_platformlinux-aarch64gcc_version15.1.0.yaml
.ci_support/linux_ppc64le_cross_target_platformlinux-ppc64legcc_version15.1.0.yaml
.ci_support/linux_ppc64le_cross_target_platformwin-64gcc_version15.1.0.yaml
.ci_support/osx_64_clang_version18.1cross_target_platformlinux-64gcc_version15.1.0.yaml
.ci_support/osx_64_clang_version18.1cross_target_platformlinux-aarch64gcc_version15.1.0.yaml
.ci_support/osx_64_clang_version18.1cross_target_platformlinux-ppc64legcc_version15.1.0.yaml
.ci_support/osx_64_clang_version19.1cross_target_platformlinux-64gcc_version15.1.0.yaml
.ci_support/osx_64_clang_version19.1cross_target_platformlinux-aarch64gcc_version15.1.0.yaml
.ci_support/osx_64_clang_version19.1cross_target_platformlinux-ppc64legcc_version15.1.0.yaml
.ci_support/osx_64_clang_version20.1cross_target_platformlinux-64gcc_version15.1.0.yaml
.ci_support/osx_64_clang_version20.1cross_target_platformlinux-aarch64gcc_version15.1.0.yaml
.ci_support/osx_64_clang_version20.1cross_target_platformlinux-ppc64legcc_version15.1.0.yaml
.ci_support/win_64_cross_target_platformwin-64gcc_version15.1.0.yaml
README.md
recipe/conda_build_config.yaml

Following on from https://github.com/conda-forge/ctng-compilers-feedstock/pull/172

GCC v15.1.0; drop v12

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_cross_target_platformlinux-64gcc_version13.4.0.yaml
.ci_support/linux_64_cross_target_platformlinux-aarch64gcc_version13.4.0.yaml
.ci_support/linux_64_cross_target_platformlinux-ppc64legcc_version13.4.0.yaml
.ci_support/linux_64_cross_target_platformwin-64gcc_version13.4.0.yaml
.ci_support/linux_aarch64_cross_target_platformlinux-64gcc_version13.4.0.yaml
.ci_support/linux_aarch64_cross_target_platformlinux-aarch64gcc_version13.4.0.yaml
.ci_support/linux_aarch64_cross_target_platformlinux-ppc64legcc_version13.4.0.yaml
.ci_support/linux_aarch64_cross_target_platformwin-64gcc_version13.4.0.yaml
.ci_support/linux_ppc64le_cross_target_platformlinux-64gcc_version13.4.0.yaml
.ci_support/linux_ppc64le_cross_target_platformlinux-aarch64gcc_version13.4.0.yaml
.ci_support/linux_ppc64le_cross_target_platformlinux-ppc64legcc_version13.4.0.yaml
.ci_support/linux_ppc64le_cross_target_platformwin-64gcc_version13.4.0.yaml
.ci_support/osx_64_clang_version18.1cross_target_platformlinux-64gcc_version13.4.0.yaml
.ci_support/osx_64_clang_version18.1cross_target_platformlinux-aarch64gcc_version13.4.0.yaml
.ci_support/osx_64_clang_version18.1cross_target_platformlinux-ppc64legcc_version13.4.0.yaml
.ci_support/osx_64_clang_version19.1cross_target_platformlinux-64gcc_version13.4.0.yaml
.ci_support/osx_64_clang_version19.1cross_target_platformlinux-aarch64gcc_version13.4.0.yaml
.ci_support/osx_64_clang_version19.1cross_target_platformlinux-ppc64legcc_version13.4.0.yaml
.ci_support/osx_64_clang_version20.1cross_target_platformlinux-64gcc_version13.4.0.yaml
.ci_support/osx_64_clang_version20.1cross_target_platformlinux-aarch64gcc_version13.4.0.yaml
.ci_support/osx_64_clang_version20.1cross_target_platformlinux-ppc64legcc_version13.4.0.yaml
.ci_support/win_64_cross_target_platformwin-64gcc_version13.4.0.yaml
README.md
recipe/conda_build_config.yaml

Just waiting for the builds from https://github.com/conda-forge/ctng-compilers-feedstock/pull/178 to come online.

GCC v13.4.0
